language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: DsI5Ebx1QpPQf/CPn8Uc+n2FS4MMEhKXije/WoqkF5vSGQSV5DtfkQsTXDF3B+yicBtR8YFM8HQUPP5HSVq90wewm0lF/k4giauSxGIb3+NpYYH8uz+sEhA4L+HgLHmiUebfhevHDGh4WBAdVUNTIzI61IMYPuJtoB4V8glimRgNwHBqvMg1UGZX/1p45FfYT2dWb2oFyrGyPiJnBnJE3hc4XvUvwX9sg+g4zI/8GEkvkjbl1NUW2GodFjfbGOHz8tkb1KayrEA+5l+ebLP1Vtpwi0HLIpIyBPlBCpbrxUR0HjPMimhSC2Io+YlQrvP2y/6EKsoXycmSKWfkrNneX6fIUc1yjEpIyS9dcnwS5wrJ4Q9DsT6eK1U2e+6PCFzgZ6nsKSO2OkBHpuIVmlzlXsEsClNx34Loa/Pp/E/pb+XdbgQ2fQ/VDA6Zhl9IUNiwc6bXhtXP1qA/wdvsTWzzn0l/etnUArkk1irIcfCFNDkyyBgU3cFTHNmZRWHf86jM2NWtq1l5k2VnOQY9er7P70ARklVuQcZDe9x246tFzfEq94oGn88fiL0bGVgTW/LmLrw5sgVAbBgAxKsyP6EFy29PtqBidFpSgKI7C3b/TZY8oCHgIkFBM0V7J0y7ZPBob3NLxCk+MVTP+DdMD2AahkjreMbnwFPbSBg3qX4fLMo=
  app: pgolubev-sample
  on:
    repo: Schtolc/sample
